name: Build Plugin

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [closed]
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build plugin
        run: ./gradlew buildPlugin

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-artifact
          path: plugin/build/distributions/ 